apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-local-net
  namespace: cert-manager
spec:
  secretName: wildcard-local-net-tls      # TLS secret name used by Ingresses
  dnsNames:
    - "*.local.net"
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer