apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cert-manager-webhook-domeneshop
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/domeneshop/cert-manager-webhook-domeneshop
  ref:
    tag: v1.0.0
