apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webhook-domeneshop
  namespace: cert-manager
spec:
  interval: 30m

  dependsOn:
    - name: cert-manager
      namespace: cert-manager

  chart:
    spec:
      chart: ./deploy/domeneshop-webhook
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-domeneshop
        namespace: flux-system
      interval: 1h

  values:
    groupName: api.domeneshop.no

    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager

    nameOverride: ""
    fullnameOverride: ""

    service:
      type: ClusterIP
      port: 443

    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi