apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homarr-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/homarr-labs/charts.git
  ref:
    # pick ONE:
    # branch: dev
    tag: homarr-8.12.1
