apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: homarr
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/homarr-labs/charts/homarr
  ref:
    semver: ">=0.0.0"
