apiVersion: v1
kind: ServiceAccount
metadata:
  name: apt-scanner
  namespace: apt-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apt-scanner
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apt-scanner
subjects:
  - kind: ServiceAccount
    name: apt-scanner
    namespace: apt-scanner
roleRef:
  kind: ClusterRole
  name: apt-scanner
  apiGroup: rbac.authorization.k8s.io