apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proton-bridge-data
  namespace: proton-bridge
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
    storageClass: longhorn-retain