apiVersion: v1
kind: Service
metadata:
  name: proton-bridge
  namespace: proton-bridge
spec:
  selector:
    app: proton-bridge
  ports:
    - name: api
      port: 8080
      targetPort: api
    - name: monitor
      port: 8081
      targetPort: monitor