apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-backups
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-odin
  resources:
    requests:
      storage: 10Gi