apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - renovate
  - github-runner
  - traefik
  - metalllb
  - cert-manager
  - uptime-kuma
  - longhorn
  - nfs-provisioner
  - media
  - monitoring
#  - huginn
  - seaweedfs
  - crafty
  - cnpg
#  - authentik