apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - HelmRepository.yaml
  - HelmRelease-grafana.yaml
  - HelmRelease-alloy.yaml
  - HelmRelease-loki.yaml
  - HelmRelease-promtail.yaml
  - pvc-geoip.yaml
  - ingress.yaml