apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-geoip
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-odin
  resources:
    requests:
      storage: 200Mi
