apiVersion: v1
kind: Service
metadata:
  name: kubevirt-manager
  namespace: kubevirt-manager
spec:
  type: ClusterIP
  selector:
    app: kubevirt-manager
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP