apiVersion: v1
kind: ConfigMap
metadata:
  name: wolweb-config
  namespace: wol
data:
  config.json: |
    {
      "host": "0.0.0.0",
      "port": 8089,
      "vdir": "",
      "bcastip": "10.0.1.255:9"
    }
  devices.json: |
    {
      "devices": [
        {
          "name": "gaming-pc",
          "mac": "88:AE:DD:1E:4F:45",
          "ip": "10.0.1.20:9"
        }
      ]
    }