apiVersion: v1
kind: ConfigMap
metadata:
  name: wolweb-config
  namespace: wol
data:
  config.json: |
    {
      "listenaddr": ":8080",
      "bcastaddr": "10.0.1.255:9",
      "devices": [
        {
          "name": "gaming-pc",
          "mac": "88:AE:DD:1E:4F:45",
          "broadcast": "10.0.1.20"
        }
      ]
    }