apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-database
  namespace: vaultwarden
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: vaultwarden
      owner: vw_user
      secret:
        name: vaultwarden-database-secret