apiVersion: v1
kind: Secret
metadata:
  name: seaweed-s3-backup
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "longhorn"
  AWS_SECRET_ACCESS_KEY: "REPLACE_ME"   # samme som i seaweed config
  AWS_ENDPOINTS: "http://s3.local.net"