apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: drewburr-labs-helm-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://drewburr-labs.github.io/helm-charts/
