apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: craftycontroller
  namespace: crafty
spec:
  interval: 15m

  chart:
    spec:
      chart: craftycontroller
      version: "0.1.7"
      sourceRef:
        kind: HelmRepository
        name: drewburr-labs-helm-charts
        namespace: flux-system
      interval: 1h

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    # Default values for panel.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    replicas: 1 # Should always be 1

    image:
      repository: registry.gitlab.com/crafty-controller/crafty-4
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: ''

    imagePullSecrets: []
    nameOverride: ''
    fullnameOverride: ''

    resources: {}

    livenessProbe:
      initialDelaySeconds: 30
      httpGet:
        path: /
        port: https
        scheme: HTTPS
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 18
      httpGet:
        path: /
        port: https
        scheme: HTTPS
    startupProbe: {}

    persistence:
      crafty-app-config:
        enabled: true
        accessModes:
          - ReadWriteOnce
        mountPath: /crafty/app/config
        requests: 1Gi
        storageClassName: longhorn-retain
      crafty-servers:
        enabled: true
        accessModes:
          - ReadWriteOnce
        mountPath: /crafty/servers
        requests: 10Gi
        storageClassName: longhorn-retain
      crafty-backups:
        enabled: false
        accessModes:
          - ReadWriteOnce
        mountPath: /crafty/backups
        requests:
        storageClassName: longhorn-retain
      crafty-logs:
        enabled: false
        accessModes:
          - ReadWriteOnce
        mountPath: /crafty/logs
        requests:
        storageClassName: longhorn-retain
      crafty-import:
        enabled: false
        accessModes:
          - ReadWriteOnce
        mountPath: /crafty/import
        requests:
        storageClassName: longhorn-retain

    additionalVolumes: []
    additionalVolumeMounts: []

    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ''

    podAnnotations: {}

    podSecurityContext:
      fsGroup: 0

    # Using the crafty user skips permission checking during container start.
    # Running as root is not reccommended, but will trigger this process to run,
    # and may resolve permission issues.
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000 # Built-in Crafty user
      runAsGroup: 0 # Required for permissions

    services:
      https:
        ingress:
          className: traefik-external
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-domeneshop
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/service.serversscheme: https
            traefik.ingress.kubernetes.io/service.serverstransport: crafty-skipverify@kubernetescrd
          hosts:
            - host: console.nebulahvelvet.no
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - console.nebulahvelvet.no
              secretName: crafty-console-tls

      minecraft:
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: "10.0.2.89"
        ports:
          - name: minecraft
            port: 25565
            protocol: TCP

    serviceMonitors: []
      # - name: minecraft-metrics
      #   endpoints:
      #     - interval: 30s
      #       path: /
      #       port: metrics
      #       scrapeTimeout: 10s
      #   selector: {}
      #   namespaceSelector:
      #     matchNames:
      #       - "{{ .Release.Namespace }}"

    sftp:
      enabled: false

      image:
        repository: atmoz/sftp
        tag: alpine

      users:
        secretKeyRef:
          name: sftp-users
          key: users

      resources: {}
      securityContext: {}

      service:
        type: ClusterIP
        annotations: {}
        port:
          name: sftp
          port: 22
          protocol: TCP

      livenessProbe:
        tcpSocket:
          port: sftp
      readinessProbe:
        tcpSocket:
          port: sftp

      additionalEnv: []

    initContainers: []

    nodeSelector: {}
    tolerations: []
    affinity: {}

  postRenderers:
  - kustomize:
      patches:
        - target:
            kind: Service
            name: craftycontroller-minecraft
          patch: |-
            apiVersion: v1
            kind: Service
            metadata:
              name: craftycontroller-minecraft
            spec:
              externalTrafficPolicy: Local