apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: crafty-internal
  namespace: crafty
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`console.local.net`)
      kind: Rule
      services:
        - name: craftycontroller-https
          port: 8443
          scheme: https
          serversTransport: crafty-crafty-skipverify