apiVersion: v1
kind: Secret
metadata:
  name: github-credentials          # <- match secretRef.name
  namespace: flux-system            # <- same ns as your GitRepository
type: Opaque
stringData:
  username: git                     # can be anything, e.g. "git" or "oauth2"
  password: ""