apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadelandraas
  namespace: hadelandraas
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-odin
  resources:
    requests:
      storage: 2Gi