apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources
  namespace: romm
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-assets
  namespace: romm
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-odin
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config
  namespace: romm
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-library
  namespace: romm
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-odin
  resources:
    requests:
      storage: 100Gi