apiVersion: v1
kind: Service
metadata:
  name: arc-listener-hl
  namespace: github-runner
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: runner-scale-set-listener
    app.kubernetes.io/instance: arc-runner-set
  ports:
    - name: dummy
      port: 80
      targetPort: 80