apiVersion: v1
kind: Service
metadata:
  name: arc-controller-hl
  namespace: github-runner
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/instance: arc
  ports:
    - name: dummy
      port: 80
      targetPort: 80