apiVersion: v1
kind: Service
metadata:
  name: arc-listener-hl
  namespace: github-runner
spec:
  type: ClusterIP
  selector:
    actions.github.com/scale-set-name: arc-runner-set
    actions.github.com/scale-set-namespace: github-runner
  ports:
    - name: dummy
      port: 8080
      targetPort: 8080