apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seaweed-s3-internal
  namespace: seaweedfs
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`s3.local.net`)
      kind: Rule
      services:
        - name: weed-s3
          port: 8333
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seaweed-files-internal
  namespace: seaweedfs
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`files.local.net`)
      kind: Rule
      services:
        - name: weed-filer
          port: 8888