apiVersion: v1
kind: Secret
metadata:
  name: seaweed-s3-config
  namespace: seaweedfs
type: Opaque
stringData:
  seaweedfs_s3_config.json: |
    {
      "identities": [
        {
          "name": "longhorn",
          "actions": [
            "Read:longhorn",
            "List:longhorn",
            "Tagging:longhorn",
            "Write:longhorn"
          ],
          "credentials": [
            { "accessKey": "longhorn", "secretKey": "...." }
          ]
        },
        {
          "name": "friend-proxmox",
          "actions": [
            "Read:friend-proxmox-backup",
            "List:friend-proxmox-backup",
            "Tagging:friend-proxmox-backup",
            "Write:friend-proxmox-backup"
          ],
          "credentials": [
            { "accessKey": "friend-proxmox", "secretKey": "CHANGE_ME_LONG_RANDOM_SECRET" }
          ]
        },
        {
          "name": "read-only",
          "actions": ["Read","List"],
          "credentials": [
            { "accessKey": "ro", "secretKey": "...<." }
          ]
        }
      ]
    }

# Notes:
# - Create bucket buckets up front with an admin identity.