apiVersion: v1
kind: Secret
metadata:
  name: seaweed-s3-config
  namespace: seaweedfs
type: Opaque
stringData:
  seaweedfs_s3_config.json: |
    {
      "identities": [
        {
          "name": "longhorn",
          "actions": ["Admin","Read","List","Tagging","Write"],
          "credentials": [
            { "accessKey": "longhorn", "secretKey": "...." }
          ]
        },
        {
          "name": "read-only",
          "actions": ["Read","List"],
          "credentials": [
            { "accessKey": "ro", "secretKey": "...<." }
          ]
        }
      ]
    }
---
Read = laste ned / lese objekter

List = liste buckets/objekter

Write = laste opp / skrive objekter

Tagging = sette/lese tags (kan ofte være greit å ha)

Admin = “alt”, inkl mer administrative operasjoner (bruk sparsomt) | MÅ HA Admin for å kunne opprette bucket