apiVersion: v1
kind: Secret
metadata:
  name: seaweed-s3-config
  namespace: seaweedfs
type: Opaque
stringData:
  seaweedfs_s3_config.json: |
    {
      "identities": [
        {
          "name": "NAVN PÅ IDENTITET",
          "actions": ["Read", "List", "Write"],
          "credentials": [
            { "accessKey": "REPLACE_ME", "secretKey": "REPLACE_ME" }
          ]
        }
      ]
    }
---
Read = laste ned / lese objekter

List = liste buckets/objekter

Write = laste opp / skrive objekter

Tagging = sette/lese tags (kan ofte være greit å ha)

Admin = “alt”, inkl mer administrative operasjoner (bruk sparsomt)