apiVersion: apps/v1
kind: Deployment
metadata:
  name: weed-s3
  namespace: seaweedfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weed-s3
  template:
    metadata:
      labels:
        app: weed-s3
    spec:
      containers:
        - name: s3
          # renovate: datasource=docker depName=chrislusf/seaweedfs
          image: chrislusf/seaweedfs:4.13
          command: ["weed", "s3"]
          args:
            - "-ip=0.0.0.0"
            - "-port=8333"
            - "-filer=weed-filer:8888"
          ports:
            - name: http
              containerPort: 8333
          readinessProbe:
            httpGet:
              path: /
              port: 8333
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8333
            initialDelaySeconds: 20
            periodSeconds: 20