apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weed-volume
  namespace: seaweedfs
spec:
  serviceName: weed-volume
  replicas: 1
  selector:
    matchLabels:
      app: weed-volume
  template:
    metadata:
      labels:
        app: weed-volume
    spec:
      containers:
        - name: volume
          # renovate: datasource=docker depName=chrislusf/seaweedfs
          image: chrislusf/seaweedfs:4.13
          args:
            - "volume"
            - "-ip=0.0.0.0"
            - "-port=8080"
            - "-dir=/data"
            - "-mserver=weed-master:9333"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteMany"]
        storageClassName: nfs-odin   # <-- bytt til din NFS StorageClass
        resources:
          requests:
            storage: 200Gi           # <-- juster