apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 21 * * *"   # hver kveld kl2100
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:43.48.2
              args:
                - "stianmjo/homelab-nebulahvelvet"
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: RENOVATE_TOKEN

                - name: RENOVATE_PLATFORM
                  value: github
                - name: RENOVATE_ENDPOINT
                  value: https://api.github.com/

                - name: RENOVATE_TIMEZONE
                  value: Europe/Oslo
                - name: LOG_LEVEL
                  value: debug
