apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard-tls
  namespace: gitlab
spec:
  secretName: gitlab-wildcard-tls
  issuerRef:
    name: letsencrypt-domeneshop
    kind: ClusterIssuer
  dnsNames:
    - git.nebulahvelvet.no
    - registry.nebulahvelvet.no
