apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: hadeland-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      imagePullSecrets:
        - name: ghcr-pull

      securityContext:
        fsGroup: 65532

      initContainers:
        - name: init-perms
          image: alpine:3.20
          command: ["sh", "-lc", "mkdir -p /data && chown -R 65532:65532 /data && chmod -R u+rwX,g+rwX /data"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: data
              mountPath: /data

      containers:
        - name: discord-bot
          image: ghcr.io/stianmjo/hadeland-bot:v0.2.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_TOKEN
            - name: DB_PATH
              value: /data/bot.db
            - name: TZ
              value: Europe/Oslo
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: discord-bot-data
