apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull
  namespace: hadeland-bot
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "",
          "password": "",
          "auth": ""
        }
      }
    }