apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sw-filer
  namespace: seaweedfs
spec:
  storageClassName: nfs-odin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi