apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: sw
  namespace: seaweedfs
spec:
  image: chrislusf/seaweedfs:4.13
  volumeServerDiskCount: 1

  master:
    replicas: 1

  volume:
    replicas: 1
    requests:
      storage: 50Gi
    storageClassName: nfs-odin

  filer:
    replicas: 1

    persistence:
      enabled: true
      storageClassName: nfs-odin
      resources:
        requests:
          storage: 10Gi

    s3:
      enabled: true
      configSecret:
        name: seaweed-s3-config
        key: seaweedfs_s3_config.json

    config: |
      [filer.options]
      buckets_folder = "/data/buckets"

      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"