apiVersion: v1
kind: PersistentVolume
metadata:
  name: dcsg2005-backup-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.2.5
    path: /var/nfs/shared/backups
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcsg2005-backup-nfs
  namespace: dcsg2005
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: dcsg2005-backup-nfs-pv
  resources:
    requests:
      storage: 100Gi