apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcsg2005-backup-nfs
  namespace: dcsg2005
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-odin
  resources:
    requests:
      storage: 5Gi