apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emulatorjs-mgmt
  namespace: emulatorjs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik-internal
  rules:
    - host: emulatorjs-mgmt.local.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emulatorjs-mgmt
                port:
                  number: 3000
