apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulatorjs-config
  namespace: emulatorjs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emulatorjs-data
  namespace: emulatorjs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 50Gi
