apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.18"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      interval: 1h

  values:
    replicaCount: 1
    strategyType: Recreate

    nfs:
      server: 10.0.2.5
      path: /var/nfs/shared/media


    storageClass:
      create: false
      provisionerName: k8s-sigs.io/nfs-odin

    leaderElection:
      enabled: true

    rbac:
      create: true

    podSecurityPolicy:
      enabled: false

    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}

    serviceAccount:
      create: true
      annotations: {}
      name: ""

    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

    labels: {}

    podDisruptionBudget:
      enabled: false
      maxUnavailable: 1
