apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-odin
provisioner: k8s-sigs.io/nfs-odin
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - vers=3
  - proto=tcp
parameters:
  archiveOnDelete: "true"
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
