apiVersion: kubevirt-manager.io/v1
kind: Image
metadata:
  name: ubuntu-noble
  namespace: kubevirt-vms
spec:
  type: http
  readableName: "Ubuntu 24.04 LTS (Noble) - Server"
  readableDescription: "Ubuntu 24.04 LTS Noble Numbat - minimal cloud image"
  http:
    url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
---
---
apiVersion: kubevirt-manager.io/v1
kind: Image
metadata:
  name: kali-linux
  namespace: kubevirt-vms
spec:
  type: http
  readableName: "Kali Linux 2024.2"
  readableDescription: "Kali Linux 2024.2 - official cloud image"
  http:
    url: "https://kali.download/cloud-images/kali-2024.2/kali-linux-2024.2-cloud-genericcloud-amd64.qcow2"