apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: "2026.2.1" # renovate: datasource=helm registryUrl=https://charts.goauthentik.io depName=authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 1h
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    authentik:
      postgresql:
        host: authentik-postgres-rw.authentik.svc.cluster.local
        name: authentik
        user: authentik

    server:
      replicas: 2

    worker:
      replicas: 2

    postgresql:
      enabled: false

    valkey:
      enabled: true

    global:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
        - name: email-templates
          configMap:
            name: authentik-templates
      volumeMounts:
        - name: media
          mountPath: /media
        - name: email-templates
          mountPath: /templates
      env:
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: AUTHENTIK_POSTGRESQL__PASSWORD
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secret
              key: secret-key
        - name: TZ
          value: Europe/Oslo
        - name: AUTHENTIK_EMAIL__HOST
          value: smtp.protonmail.ch
        - name: AUTHENTIK_EMAIL__PORT
          value: "587"
        - name: AUTHENTIK_EMAIL__USE_TLS
          value: "true"
        - name: AUTHENTIK_EMAIL__USE_SSL
          value: "false"
        - name: AUTHENTIK_EMAIL__TIMEOUT
          value: "30"
        - name: AUTHENTIK_EMAIL__USERNAME
          valueFrom:
            secretKeyRef:
              name: authentik-smtp-secret
              key: username
        - name: AUTHENTIK_EMAIL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-smtp-secret
              key: password
        - name: AUTHENTIK_EMAIL__FROM
          value: "Authentik <noreply@nebulahvelvet.no>"
        - name: AUTHENTIK_STORAGE__MEDIA__BACKEND
          value: "file"
        - name: AUTHENTIK_STORAGE__MEDIA__FILE__PATH
          value: "/media"
