apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - HelmRepository.yaml
#  - HelmRelease.yaml
  - postgres-cluster.yaml
#  - scheduled-backup.yaml
#  - media-pvc.yaml
#  - ingress.yaml
#  - middleware.yaml
