apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  instances: 3
  primaryUpdateStrategy: supervised

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-credentials

  storage:
    size: 5Gi
    storageClass: longhorn