apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-postgres-daily
  namespace: authentik
spec:
  schedule: "0 20 * * *" # 21:00 Europe/Oslo (UTC+1)
  backupOwnerReference: self
  cluster:
    name: authentik-postgres
