apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: proton-relay
spec:
  provider:
    webhook:
      url: "http://proton-relay.external-secrets.svc/secret/{{ .remoteRef.key }}"
      result:
        jsonPath: "$.value"
      headers:
        Authorization: "Bearer {{ .auth.bridgeToken }}"
      secrets:
        - name: auth
          secretRef:
            namespace: external-secrets
            name: proton-relay